name: docs
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: 
      - completed
  push:
    branches: 
      - master
env:
  HOME: /root
defaults:
  run:
    shell: bash  

jobs:
  build:
    runs-on: ubuntu-20.04
    container: fastai/fastai
    steps:
    - uses: actions/checkout@v2
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
    - uses: fastai/workflows/build-docs@master
      with:
        username: jeremyphoward
        hostname: ps625762.dreamhostps.com
        dest_path: fastscript.fast.ai
        ssh_key: ${{ secrets.DH_KEY }}
